### ISSUE TITLE
建议将“Manly修图工具 & Bear笔记本 & Picsew截图”内购脚本合并为一个文件

### ISSUE THREAD

**Issue by fangpidedongsun** [wubulaba/surgescript#1]
建议将“Manly修图工具 & Bear笔记本 & Picsew截图”内购脚本合并为一个文件，这样就不用每次都注释掉不用的脚本了。
if(bundle_id == "bundle_id")
{
  脚本内容
}

**Comment by wubulaba** [comment]
已增加verifyReceipt_allinone.js
