### ISSUE TITLE
Lensa的脚本怎么使用

### ISSUE THREAD

**Issue by sirsunknight** [wubulaba/surgescript#2]
大佬，怎么获得订阅期限？我看我的记录里没有MITM

**Comment by wubulaba** [comment]
hostname = subscription-service.neuralprisma.com

Lensa.js = requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/wubulaba/surgescript/master/Script/Lensa.js,pattern=^https?:\/\/subscription-service\.neuralprisma\.com\/subscription_get,type=http-response

**Comment by wubulaba** [comment]
不行了吗？你添加到配置文件试一下 这个修图app不好用我给卸载了 一直没测试

**Comment by sirsunknight** [comment]
好的，感谢，我再试试，我主要喜欢这个APP的自动虚化背景
